In [4]:
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit as spl

C:\Users\ediso\AppData\Local\Temp\ipykernel_22220\4049600394.py:4: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv("./2015/2015.csv",engine="python", error_bad_lines=False)
Skipping line 2878356: unexpected end of data

,filedate,serialno,sporder,st,puma,wt,age,sex,mar,education,...,spm_fedtax,spm_fedtaxbc,spm_eitc,spm_fica,spm_sttax,spm_capwkccxpns,spm_wkxpns,spm_childcarexpns,spm_medxpns,spm_premium
0,20211015,1,1,17,1703106,110,45,2,1,4,...,28809.24,28809.24,0.0,9726,6051.25,2325.4810,2325.4810,0.0,2558.706615,1803.100775
1,20211015,1,2,17,1703106,130,47,1,1,4,...,28809.24,28809.24,0.0,9726,6051.25,2325.4810,2325.4810,0.0,2558.706615,1803.100775
2,20211015,1,3,17,1703106,158,16,1,5,0,...,28809.24,28809.24,0.0,9726,6051.25,2325.4810,2325.4810,0.0,2558.706615,1803.100775
3,20211015,2,1,48,4801907,91,61,1,1,4,...,1627.50,1627.50,0.0,2678,0.00,2044.8195,2044.8195,0.0,5235.824818,0.000000
4,20211015,2,2,48,4801907,82,67,2,1,1,...,1627.50,1627.50,0.0,2678,0.00,2044.8195,2044.8195,0.0,5235.824818,0.000000

In [42]:
df = pd.read_sas("./spm_pu_2019.sas7bdat")
df.head()

split = spl(n_splits = 1, test_size = 0.035, random_state=12)
for train_index, test_index in split.split(df, df['offpoor']):
    strat_train_set = df.iloc[train_index]
    strat_test_set = df.iloc[test_index]

print(f"{df.shape} DF,{strat_train_set.shape} train, {strat_test_set.shape} test")

(3088232, 46) DF,(2980143, 46) train, (108089, 46) test

In [43]:
strat_test_set.to_csv("./Samples/2019_sample.csv", index=False)